import Breadcrumb from '../components/Breadcrumb'
import ProductsRow from '../components/ProductsRow'
import SectionTitle from '../components/SectionTitle'

export const metadata = {
  title: "ريواش | المتجر",
  description: "Generated by Rewash",
};

export default function Store() {
  return (
    <>
      <Breadcrumb title={"المتجر"} />

      <section id="store_page" class="pb-md-5 pb-3">
        <div class="container">
          <div class="mb-4">
            <SectionTitle title={"اكتشف منتجات ريواش"} body={"اشترِ منتجات العناية بالسيارة التي نستخدمها في خدماتنا."} />
          </div>
          
          <div class="row row-cols-1 row-cols-md-4 g-4">
            <ProductsRow />
          </div>
        </div>
      </section>
    </>
  );
}