import React from 'react'
import Breadcrumb from '../components/Breadcrumb'

export const metadata = {
  title: "ريواش | الشراكات",
  description: "Generated by Rewash",
};

export default function Partnerships() {
  return (
    <>
      <Breadcrumb title={"الشراكات"} />
    </>
  )
}
