import React from 'react'
import Breadcrumb from '../components/Breadcrumb'

export const metadata = {
  title: "ريواش | تواصل معنا",
  description: "Generated by Rewash",
};

export default function Contact() {
  return (
    <>
      <Breadcrumb title={"تواصل معنا"} />
    </>
  )
}
