import React from 'react'
import Breadcrumb from '../components/Breadcrumb'
import SectionTitle from '../components/SectionTitle'
import PricingRow from '../components/PricingRow'

export const metadata = {
  title: "ريواش | الباقات",
  description: "Generated by Rewash",
};

export default function Pricing() {
    return (
        <>
            <Breadcrumb title={"الباقات"} />
    
            <section id="store_pricing" class="pb-md-5 pb-3">
                <div class="container">
                    <div class="mb-4">
                        <SectionTitle title={"اكتشف باقات ريواش"} body={"إختر الباقة المناسبة للعناية بسيارتك."} />
                    </div>
                    
                    <div class="row row-cols-1 row-cols-md-3 g-4">
                        <PricingRow />
                    </div>
                </div>
            </section>
        </>
    )
}
