import BookingModal from "./components/BookingModal";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Rewash",
  description: "Generated by Rewash",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <Header />
        {children}
        <BookingModal />
        <Footer />
        <script src="js/main.js"></script>
      </body>
    </html>
  );
}
