import BookingModal from "./components/BookingModal"
import Footer from "./components/Footer"
import Header from "./components/Header"
import { fetchInfo } from "./utils/api";
import "./globals.css";

let post = [];

try {
  post = await fetchInfo();

} catch (error) {
  console.error('Error fetching Site Info:', error);
};

export const metadata = {
  title: post?.site_name || 'Rewash',
  description: post?.site_description || 'Generated by Rewash',
};

export default async function RootLayout({ children }) {

  return (
    <html lang="ar" dir="rtl">
      <body>
        <Header post={post} />
        {children}
        <BookingModal />
        <Footer post={post} />
        <script src="js/main.js"></script>
      </body>
    </html>
  );
}