import Breadcrumb from '../components/Breadcrumb'
import ServicesCard from '../components/ServicesCard'

export const metadata = {
  title: "ريواش | الخدمات",
  description: "Generated by Rewash",
};

export default function Services() {
  return (
    <>
      <Breadcrumb title={"الخدمات"} />

      <section id="services_page" class="pb-0">
        <div class="container">
          <div class="card h-50vh d-none d-md-block bg-img border-0 p-5" style={{backgroundImage: "url('/image/jan-kopriva-sh_7sFEFICI-unsplash.png')"}}></div>

          <div class="service_card pt-0 my-4 my-md-0">
            <div class="px-md-5 px-0">
              <ServicesCard />
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
