import React from 'react'
import Breadcrumb from '../components/Breadcrumb'

export const metadata = {
  title: "ريواش | الأسئلة الشائعة",
  description: "Generated by Rewash",
};

export default function FQ() {
  return (
    <>
      <Breadcrumb title={"الأسئلة الشائعة"} />
    </>
  )
}
