import React from 'react'
import Breadcrumb from '../components/Breadcrumb'
import SectionTitle from '../components/SectionTitle'
import Accordion from '../components/Accordion';

export const metadata = {
  title: "ريواش | الأسئلة الشائعة",
  description: "Generated by Rewash",
};

export default function FQ() {
  return (
    <>
      <Breadcrumb title={"الأسئلة الشائعة"} />

      <section id="f&q_page" class="pb-4">
        <div class="container">
          <div class="mb-4">
            <SectionTitle title={"الأسئلة الشائعة"} body={"إجابات لأكثر الأسئلة المتداولة حول ريواش"} />
          </div>

          <div class="accordion" id="accordionExample">
            <Accordion />
          </div>
        </div>
      </section>
    </>
  )
}
