import React from 'react'
import Breadcrumb from '../components/Breadcrumb'
import SectionTitle from '../components/SectionTitle'

export const metadata = {
  title: "ريواش | الأسئلة الشائعة",
  description: "Generated by Rewash",
};

export default function FQ() {
  return (
    <>
      <Breadcrumb title={"الأسئلة الشائعة"} />

      <section id="store_page" class="pb-md-5 pb-3">
        <div class="container">
          <div class="mb-4">
            <SectionTitle title={"الأسئلة الشائعة"} body={"إجابات لأكثر الأسئلة المتداولة حول ريواش"} />
          </div>
          
          <div class="row row-cols-1 row-cols-md-4 g-4">
          </div>
        </div>
      </section>
    </>
  )
}
