import React from 'react'
import Breadcrumb from '../components/Breadcrumb'

export const metadata = {
  title: "ريواش | المدونة",
  description: "Generated by Rewash",
};

export default function Blog() {
  return (
    <>
      <Breadcrumb title={"المدونة"} />
    </>
  )
}
