import Breadcrumb from '../components/Breadcrumb';
import FeaturePost from '../components/FeaturePost';
import MostCommonPost from '../components/MostCommonPost';
import PostCard from '../components/PostCard';

export const metadata = {
  title: "ريواش | المدونة",
  description: "Generated by Rewash",
};

async function getPosts() {
  const res = await fetch('https://rewash-store.bright-ignite.com/api/blogs', {
    cache: 'no-store',
  });
  const json = await res.json();

  if (json?.status && Array.isArray(json.data)) {
    return json.data.map((item) => ({
      id: item.id,
      title: item.title?.ar || item.title?.en || "",
      description: item.description?.ar || item.description?.en || "",
      image: item.image,
      slug: item.slug?.ar || item.slug?.en || "",
      tag: item.tag?.ar || item.tag?.en || "",
    }));
  }

  return [];
}

export default async function Blog() {
  const posts = await getPosts();

  const featurePost = posts[0];
  const mostCommonPosts = posts.slice(1, 4);
  const otherPosts = posts.slice(4);

  return (
    <>
      <Breadcrumb title={"المدونة"} />

      <section id="blog_page" class="pb-4">
        <div class="container">
          <div class="row mb-md-4 mb-3 g-md-4 g-3">
            <div class="col-12 col-md-8">
              <FeaturePost post={featurePost} />
            </div>

            <div class="col-12 col-md-4 d-flex flex-column justify-content-between">
              <h1 class="fw-bold fs-6 mt-0 mb-2">الأكثر شيوعاً</h1>
              <MostCommonPost posts={mostCommonPosts} />
            </div>
          </div>

          <div class="row row-cols-1 row-cols-md-3 g-md-4 g-3">
            {otherPosts.map((post) => (
              <PostCard key={post.id} post={post} />
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
