import { NextIntlClientProvider, hasLocale } from "next-intl"
import { notFound } from "next/navigation"
import { routing } from "@/i18n/routing"
import BookingModal from "./components/BookingModal"
import Footer from "./components/Footer"
import Header from "./components/Header"
import { fetchInfo } from '../utils/api';
import "../globals.css";

let post = [];

try {
  post = await fetchInfo();

} catch (error) {
  console.error('Error fetching Site Info:', error);
};

export const metadata = {
  title: post?.site_name || 'Rewash',
  description: post?.site_description || 'Generated by Rewash',
};


export default async function RootLayout({ children, params }) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const isRTL = locale.startsWith('ar');

  return (
    <html lang={locale} dir={isRTL ? 'rtl' : 'ltr'}>
      <head>
        <link
          rel="stylesheet"
          href={isRTL ? '/css/main.rtl.css' : '/css/main.css'}
        />
        <link rel="stylesheet" href="/css/bundle.css" />
      </head>
      <body>
        <NextIntlClientProvider>
          <Header post={post} />
          {children}
          <BookingModal />
          <Footer post={post} />
        </NextIntlClientProvider>
        <script src="/js/main.js"></script>
      </body>
    </html>
  );
}