import Hero from './components/Hero'
import Features from './components/Features'
import AboutUs from './components/AboutUs'
import HowItWorks from './components/HowItWorks'
import Services from './components/Services'
import Products from './components/Products'
import AppPromotion from './components/AppPromotion'
import Testimonials from './components/Testimonials'
import PricingSection from './components/PricingSection'

export const metadata = {
  title: "ريواش | الرئيسية",
  description: "Generated by Rewash",
};

export default async function Home({ params }) {
  return (
    <>
      <Hero locale={params.locale} />
      <Features locale={params.locale} />
      <AboutUs locale={params.locale} />
      <HowItWorks locale={params.locale} />
      <Services locale={params.locale} />
      <Products locale={params.locale} />
      <AppPromotion locale={params.locale} />
      <PricingSection locale={params.locale} />
      <Testimonials locale={params.locale} />
    </>
  );
}